### ISSUE TITLE
System tests framework - missing functionality

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#176]
**Tasks**:
- [x] Pack Slang runtime in the content verifier jar
- [x] Add an input to the main that states if we want to run tests.
- [x] Add method for parse the inputs yaml file to get inputs & description for all the test cases in the file
- [x] Add method for triggering slang flow test with a set of inputs from the test case file
- [x] result
- [x] update the build of the slang-content to pass the parameters to the verifier in the new way ( -Dpath=... -DtestPath=...)
- [x] support test case that expects an exception
- [x] Use the description for printing in the log.info the test case running, and for printing to sys out in case of failure
- [x] Support system properties
- [x] change artifact name to be something like *slang-build-tool*
- [x] Outputs support
- [ ] Support test suites
- [x] Add unit tests
